### ISSUE TITLE
Баг: используется nanos вместо nano в decimal2quotation

### ISSUE THREAD

**Issue by akolob92** [betslus1/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS#2]
В proto описано MoneyValue с полями units и nano. В SDK в методе decimal2quotation приводится к формату { units: 0, nanos: 0 }. Пример - при выставлении лимитной заявки дробная часть откидывается из-за бага. 
Возможно в других методах тоже надо заменить поле.

**Comment by betslus1** [comment]
Спасибо, забавно, что никто не заметил за год (видимо как и я отправляют с isEncodeRequest=false). Видимо путаницу внесло то что в timestamp именно nanos.
Поправил
